### ISSUE TITLE
Implement Beredskapsportalen logo

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [K-pro-SafeTec/Emergency-Response-Portal#145]
We have a PDF, but we would like this to be extracted as SVG if possible.

**Comment by wfeiring** [comment]
Like this?
![screenshot 2018-10-24 at 08 15 52](https://user-images.githubusercontent.com/22595827/47410123-19d72900-d765-11e8-8bdc-07fb4b75adc5.jpg)

**Comment by JamiesWhiteShirt** [comment]
It was requested that it should be placed below the app bar, above the nav buttons. The Safetec logo should stay where it was.

**Comment by wfeiring** [comment]
hæ

Med vennlig hilsen,
William Høivik Feiring


Den ons. 24. okt. 2018 kl. 10:32 skrev Erlend Åmdal <
notifications@github.com>:
